language: go

sudo: false

os:
  - linux

go:
  - 1.4
  - 1.5

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
 - go get ./...
 - go get -u github.com/golang/lint/golint
 - go get -u golang.org/x/tools/cmd/goimports

script:
 - go vet .
 - diff <(goimports -d .) <(printf "")
 - diff <(golint .) <(printf "")
 - go test -v -cpu=2 .
 - go test -v -cpu=1,2,4 -short -race .
 - $HOME/gopath/bin/goveralls -service=travis-ci
